name: test-githubactions
on: push
jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
           node-version: 18
      - name: install deped
        run: npm ci 
      - name: install deped
        run: npm test
